variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy


build:
  image: node:latest
  script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/


test:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  needs: [build]
  before_script:
    - apk add --update --no-cache git npm
  script:
    # - hugo --enableGitInfo -b "https://jhilker.gitlab.io"
    - npm ci --cache .npm --prefer-offline
    - hugo --minify -b "https://jhilker.gitlab.io"
  except:
    - main

pages:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  needs: [build]
  before_script:
    - apk add --update --no-cache git npm
  script:
    # - hugo --enableGitInfo -b "https://jhilker.gitlab.io"
    - npm ci --cache .npm --prefer-offline
    - hugo --minify -b "https://jhilker.gitlab.io"
  artifacts:
    paths:
      - public
  only:
    - main
