baseURL: https://jhilker1.github.io/
languageCode: en-us
title: Jacob's Website
theme:
- omniscient

menus:
  main:
    - name: Home
      identifier: home
      url: /
      weight: 1

    - name: About
      identifier: about
      url: /about/
      weight: 2

    - name: Resumé
      identifier: resume
      url: /resume/
      weight: 3

    - name: Projects
      identifier: projects
      url: /projects/
      weight: 4

    - name: Blog
      identifier: blog
      url: /blog/
      weight: 5

    - name: Recent Posts
      identifier: recents
      url: /blog/
      weight: 1
      parent: blog

    - name: Blog Archive
      identifier: archive
      url: /archive/
      weight: 2
      parent: blog

    - name: RSS Feed
      identifier: feed
      url: /blog/feed.xml
      weight: 3
      parent: blog

params:
  title: Jacob's Website
  author: Jacob Hilker
  description: A front-end developer, who enjoys using Emacs, Hugo, Python, and Tailwind. Currently looking for work.
  profilePic: img/jhilker.webp
  socials:
    - name: GitLab
      url: https://gitlab.com/jhilker/
      icon: "fab fa-gitlab"

    - name: GitHub
      url: https://github.com/jhilker1/
      icon: "fab fa-github"

    - name: LinkedIn
      url: https://linkedin.com/in/jhilker/
      icon: "fab fa-linkedin"

    - name: Dev.To
      url: https://dev.to/jhilker/
      icon: "fab fa-dev"

    - name: CodePen
      url: https://codepen.io/hilkerj/
      icon: "fab fa-codepen"

    - name: RSS Feed
      url: /blog/feed.xml
      icon: "fas fa-rss"

    - name: Email
      url: mailto:jacob.hilker2@gmail.com
      icon: "fas fa-envelope"



build:
  writeStats: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: nord
    tabWidth: 4

permalinks:
  blog: ":section/:year/:month/:slug"

outputFormats:
  RSS:
    baseName: feed
    mediatype: "application/rss+xml"

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html