#+title: About Me
#+hugo_draft: false
#+hugo_section: /
#+hugo_bundle: about
#+export_file_name: index

Hello! I'm Jacob, a former student of the University of Mary Washington. I graduated with a major in Computer Science with a minor in cybersecurity.  Although I majored in cybersecurity, I found that it really wasn't what I was looking for - my original plan was to minor in political science, but the closest thing the university had was International Relations, which wasn't exactly what I was looking for - this was also around the time the [[wiki:Facebook%E2%80%93Cambridge_Analytica_data_scandal][Facebook-Cambridge Analytica scandal]] was coming to light, and so I figured that cybersecurity was going to become very quickly involved with political science.


Beyond software, I have a deep love of games, both tabletop and video games. If you had to ask me what my favorite video game is, I would have to say Super Metroid, from the SNES. I feel like a lot of it boils down to the individual elements, rather than the game as a whole.


I also enjoy worldbuilding. My two most recent projects are [[https://brokenthrones.jhilker.com][Broken Thrones]], an alt-history/low fantasy setting, and [[https://shatteredskies.jhilker.com/][Shattered Skies]], a Metroid-meets-Halo-meets-Destiny, gritty sci-fi setting.

Outside of games and worldbuilding, I also develop themes for the static site generator [[https://gohugo.io][Hugo]]. I'm currently working on two at the moment - [[github:jhilker1/hugo-all-for-one][All For One]], an all-in-one blog, portfolio, and CV theme, as well as a variant of it for wikis, which I am calling [[github:jhilker1/hugo-halfmoon-wiki][Halfmoon Wiki]] until I can come up with a better name for it.
