#+title: Home
#+hugo_section: /
#+hugo_draft: false
#+macro: featured @@hugo:{{<featured count="$1">}}@@
#+macro: recents @@hugo:{{<recents count="$1">}}@@
#+export_file_name: _index

* HELLO WORLD
  Hello there, and welcome to my website. This currently houses my resume (both as a webpage and as a [[/uploads/jhilker_cv.pdf][PDF]]), as well as some of the projects I've been working on. I'm working on a blog currently, but that will be up sometime in the future. This site was written in Emacs' Org-Mode, using Hugo as a static site generator. This site is using my own [[https://github.com/jhilker1/hugo-all-for-one][All for One]] theme for Hugo (though with some very minor modifications and CSS changes), as well as the wrapper from Luis Fuentes' [[https://gitlab.com/luisfuentes/resume/][resume project]] on Gitlab.

* ABOUT ME
  I graduated from the University of Mary Washington in May 2021, with a Bachelor's of Science in computer science, and a minor in cybersecurity.

  I've been a drummer since about 6th grade, and I've been teaching myself guitar on and off since sophomore year of high school. Most recently, in January 2021 I started teaching myself bass. As far as my hobbies outside of code and music, I enjoy worldbuilding and games (both video games and tabletop games, especially tabletop role-playing games.) Feel free to explore around.

* FEATURED POSTS
These posts are the ones that I find the most interesting.
{{{featured(3)}}}

* RECENT POSTS
Interested in some of the things I write on my blog? Check them out here.
{{{recents(3)}}}
